sudo: required
language: python
python: 3.8
services:
- docker

jobs:
  include:
  - stage: Check code quality
    before_install:
    - python -m pip install --upgrade pip
    install:
    - pip install flake8 black
    script:
    - flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - black --check .

  - stage: build docker image
    script:
    - sed -i "s/development/$TRAVIS_COMMIT/g" version.py
    - docker build -t tullingegymnasium/booking_app:latest .
    deploy:
      skip_cleanup: true
      provider: script
      script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin && docker push tullingegymnasium/booking_app:latest
      on:
        branch: master
    after_deploy:
    - rm -rf /home/travis/.docker/config.json
