version: '3.7'

services:
  mysql:
    image: mysql
    environment:
      MYSQL_DATABASE: 'booking'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'do-not-use-in-production'
      MYSQL_ROOT_PASSWORD: 'do-not-use-in-production'

  redis:
    image: redis