version: "3.7"

services:
  redis:
    image: redis
    restart: always
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: "booking"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_PASSWORD}"
    volumes:
      - mysql:/var/lib/mysql
  app:
    image: "ghcr.io/hejduk-se/tgy-booking:latest"
    restart: always
    environment:
      MYSQL_HOST: "mysql"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      REDIS_HOST: "redis"
      APP_URL: "${APP_URL}"
      GOOGLE_CLIENT_ID: "${GOOGLE_CLIENT_ID}"
      GOOGLE_CLIENT_SECRET: "${GOOGLE_CLIENT_SECRET}"
      GSUITE_DOMAIN_NAME: "${GSUITE_DOMAIN_NAME}"
      CUSTOM_FOOTER: "${CUSTOM_FOOTER}"
      PORT: "${PORT}"
    depends_on:
      - mysql
      - redis
    ports:
      - "127.0.0.1:${PORT}:${PORT}"
    expose:
      - "${PORT}"

volumes:
  mysql:
